### ISSUE TITLE
How can I call method and get results?

### ISSUE THREAD

**Issue by luzik** [mcw0/Tools#14]
```
[Console]# service -h
[*] [Usage]
    service  (dump all remote services)
    service <service> (dump methods for <service>)
    service all (dump all remote services methods)
    service help [<service>|all] ("system" looks like only have builtin help)
    service [<service>|<all>] [save <filename>] (Save JSON to <filename>)
```

but I can run

```
[Console]# service magicBox.getSerialNo
[+] Services: Done
[-] Failure to fetch: magicBox
[-] Empty

OR

[Console]# service magicBox getSerialNo
[q] Services: Start
```

I believe that method was run, but don't know how to get results

**Comment by mcw0** [comment]
[Console]# service - Will return all services
[Console]# service magicBox - Will return 'services methods'; such as: magicBox.getSerialNo, magicBox.reboot... etc

There is very few 'services methods' that do not require 'params', what you would like to do would be great, but unfortunately do not work (due to the requirements of 'params').
